name: Unit tests 02_your_code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd 02_your_code/subscription_manager_base/
          pip install -r requirements/test.txt
      - name: Unit tests
        run: |
          cd 02_your_code/subscription_manager_base/
          pytest --cov="."  --cov-report term-missing --cov-fail-under=90
